#!/bin/bash

PACKR_PATH="packr"
PACKR_VERSION="4.0.0"
PACKR_JAR="packr-all-${PACKR_VERSION}.jar"
PACKR_JAR_PATH="${PACKR_PATH}/${PACKR_JAR}"
PLATFORM="windows64"

if [[ $1 == "linux" ]] || [[ $1 == "linux64" ]]; then
	PLATFORM="linux64"
fi

if [ ! -d "${PACKR_PATH}/jre/jre_${PLATFORM}" ]; then
  echo "It seems you don't have a packaged JRE yet. So we are packing it for you with jlink..."
  mkdir -p packr/jre
  jlink --add-modules java.base,java.datatransfer,java.xml,java.prefs,java.desktop,jdk.unsupported --output packr/jre/jre_$PLATFORM
fi

if [ ! -f "${PACKR_JAR_PATH}" ]; then
  echo "It seems you don't have packr yet. So we are downloading ${PACKR_JAR} from GitHub..."
  URL=$(curl -L -s https://api.github.com/repos/libgdx/packr/releases | grep -o -E "https://(.*)${PACKR_JAR}")
  curl -L -s $URL -o ${PACKR_JAR_PATH}
fi

echo "Packing the game for ${PLATFORM} with ${PACKR_JAR}..."
echo

VERSION=$(cat build.gradle | grep "version = '" | cut -d"'" -f 2)

java -jar $PACKR_JAR_PATH \
  --platform $PLATFORM \
  --jdk "${PACKR_PATH}/jre/jre_${PLATFORM}" \
  --useZgcIfSupportedOs \
  --executable imperialist-collector \
  --classpath "desktop/build/libs/desktop-${VERSION}.jar" \
  --mainclass com.willian.imperialist.DesktopLauncher \
  --vmargs Xmx1G \
  --vmargs Xms256m \
  --output "desktop/build/target/release-${VERSION}-${PLATFORM}"

echo
echo "Finished packing. If packr didn't spit any errors the final package must be at desktop/build/target."
